version: '2.2'
services:
  /sensors-api/:
    restart: always
    build: .
    ports:
      - "9000:9000"
    env_file:
      - env/development.env
    command: "sensors-api"
    container_name: sensors-api
    networks:
      golang:
        aliases:
          - sensors-api
networks:
  golang:
    external: true