apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: /sensors/
    ns: production
  name: sensors
  namespace: production
spec:
  replicas: 0
  selector:
    matchLabels:
      app: /sensors/
      ns: production
  template:
    metadata:
      labels:
        app: /sensors/
        ns: production
      namespace: production
    spec:
      containers:
        - command:
            - sensors
          env:
            - name: POWER_PLANT_MONITORING_SQL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: infrastructure
                  key: SQL_DB_HOST
            - name: POWER_PLANT_MONITORING_SQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: infrastructure
                  key: SQL_DB_NAME
            - name: POWER_PLANT_MONITORING_SQL_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: infrastructure
                  key: SQL_DB_USER
            - name: POWER_PLANT_MONITORING_SQL_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: infrastructure
                  key: SQL_DB_PASS
          envFrom:
            - configMapRef:
                name: sensors
          image: registry.zucchinidev.com/sensors:v1.0.0-rc
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /status
              port: 9000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: sensors
          ports:
            - containerPort: 9000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /status
              port: 9000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: zucchinidev-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
