apiVersion: v1
kind: Service
metadata:
  name: sensors
  labels:
    app: /sensors/
    ns: production
  namespace: production
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: /sensors/
    ns: production
  type: ClusterIP

